version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/language-server"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directories:
      - '**/*'
    schedule:
      interval: "daily"
    commit-message:
      prefix: "github-actions"
      include: "scope"
